#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# ALFRED MONOREPO - INSTALLATION HOOK
# ═══════════════════════════════════════════════════════════════════
#
# Deterministic installation script for the Alfred monorepo.
# All output uses structured markers for agent parsing:
#   ✅ = Success
#   ❌ = Error (blocking)
#   ⚠️ = Warning (non-blocking)
#
# Usage: bash .agent/hooks/setup-init.sh
# Or via: just install
#
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$ROOT_DIR"

# Timing
START_TIME=$(date +%s)

echo "═══════════════════════════════════════════════════════════════"
echo "ALFRED MONOREPO - INSTALLATION HOOK"
echo "═══════════════════════════════════════════════════════════════"
echo "Timestamp: $(date -Iseconds)"
echo "Working Directory: $ROOT_DIR"
echo "═══════════════════════════════════════════════════════════════"

# ───────────────────────────────────────────────────────────────────
# STEP 1: Prerequisites
# ───────────────────────────────────────────────────────────────────
echo ""
echo "▶ STEP 1: Checking prerequisites..."

# Node.js
if ! command -v node &> /dev/null; then
    echo "❌ ERROR: Node.js not found"
    echo "  Install from https://nodejs.org or use nvm"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 22 ]; then
    echo "❌ ERROR: Node.js 22+ required. Found: $(node -v)"
    echo "  Fix: nvm use 22 || nvm install 22"
    exit 1
fi
echo "  ✅ Node.js: $(node -v)"

# Bun
if ! command -v bun &> /dev/null; then
    echo "❌ ERROR: Bun not found"
    echo "  Install from https://bun.sh"
    echo "  Fix: curl -fsSL https://bun.sh/install | bash"
    exit 1
fi
echo "  ✅ Bun: $(bun -v)"

# Git (optional but recommended)
if command -v git &> /dev/null; then
    echo "  ✅ Git: $(git --version | cut -d' ' -f3)"
else
    echo "  ⚠️ WARN: Git not found (optional)"
fi

# Docker (optional)
if command -v docker &> /dev/null; then
    echo "  ✅ Docker: $(docker --version | cut -d' ' -f3 | tr -d ',')"
else
    echo "  ⚠️ WARN: Docker not found (optional, needed for database)"
fi

echo "  ✅ Prerequisites verified"

# ───────────────────────────────────────────────────────────────────
# STEP 2: Dependencies
# ───────────────────────────────────────────────────────────────────
echo ""
echo "▶ STEP 2: Installing dependencies..."

# Try frozen lockfile first (faster, stricter)
if bun install --frozen-lockfile 2>&1; then
    echo "  ✅ Dependencies installed (frozen lockfile)"
else
    echo "  ⚠️ WARN: Frozen lockfile failed, trying regular install..."
    if bun install 2>&1; then
        echo "  ✅ Dependencies installed"
    else
        echo "❌ ERROR: Dependency installation failed"
        exit 1
    fi
fi

# ───────────────────────────────────────────────────────────────────
# STEP 3: Environment
# ───────────────────────────────────────────────────────────────────
echo ""
echo "▶ STEP 3: Configuring environment..."

if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        echo "  ✅ Created .env from .env.example"
        echo "  ⚠️ WARN: Review .env and configure secrets before production use"
    else
        echo "  ⚠️ WARN: No .env.example found, creating minimal .env"
        cat > .env << 'ENVEOF'
# Alfred Monorepo - Development Environment
# Generated by setup-init.sh

NODE_ENV=development
LOG_LEVEL=debug
ALFRED_ENV=local

# Database (uncomment and configure for database features)
# DATABASE_URL=postgresql://postgres:postgres@localhost:5432/alfred_dev

# Add additional configuration as needed
# See .env.example for all available options
ENVEOF
        echo "  ✅ Created minimal .env"
    fi
else
    echo "  ✅ .env already exists"
fi

# ───────────────────────────────────────────────────────────────────
# STEP 4: Build
# ───────────────────────────────────────────────────────────────────
echo ""
echo "▶ STEP 4: Building packages..."

if bun run build 2>&1; then
    echo "  ✅ Build complete"
else
    echo "❌ ERROR: Build failed"
    echo "  Check the output above for specific errors"
    exit 1
fi

# ───────────────────────────────────────────────────────────────────
# STEP 5: Git Hooks
# ───────────────────────────────────────────────────────────────────
echo ""
echo "▶ STEP 5: Setting up git hooks..."

if [ -d .git ]; then
    if bun run prepare 2>&1; then
        echo "  ✅ Git hooks configured"
    else
        echo "  ⚠️ WARN: Git hooks setup failed (non-blocking)"
    fi
else
    echo "  ⚠️ WARN: Not a git repository, skipping hooks"
fi

# ───────────────────────────────────────────────────────────────────
# STEP 6: Verification
# ───────────────────────────────────────────────────────────────────
echo ""
echo "▶ STEP 6: Verification..."

echo "  Running type-check..."
if bun run type-check 2>&1; then
    echo "  ✅ Type check passed"
else
    echo "❌ ERROR: Type check failed"
    echo "  Run 'bun run type-check' to see specific errors"
    exit 1
fi

echo "  Running lint (quick)..."
if bun run lint:fast 2>&1; then
    echo "  ✅ Lint check passed"
else
    echo "  ⚠️ WARN: Lint issues found (run 'bun run lint:fix' to auto-fix)"
fi

# ───────────────────────────────────────────────────────────────────
# SUMMARY
# ───────────────────────────────────────────────────────────────────
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ INSTALLATION COMPLETE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Duration: ${DURATION} seconds"
echo "Node: $(node -v)"
echo "Bun: $(bun -v)"
echo ""
echo "Quick Start Commands:"
echo "  just dev          - Start development servers"
echo "  just doctor       - Run health diagnostics"
echo "  just test         - Run tests"
echo "  just lint         - Run linter"
echo ""
echo "For agents:"
echo "  Review AGENT_RULES.md for coding standards"
echo "  Run /prime workflow before major tasks"
echo ""
echo "Exit Code: 0"
